/**
 * MockDemoAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Employee = require('./Employee');

/**
 * Creates an instance of Boss
 */
class Boss extends Employee {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.promotedAt = this.constructor.getValue(obj.promotedAt);
        this.assistant = this.constructor.getValue(obj.assistant);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            {
                name: 'promotedAt',
                realName: 'promotedAt',
                isDateTime: true,
                dateTimeValue: 'unixtimestamp',
            },
            { name: 'assistant', realName: 'assistant', type: 'Employee' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {
            Boss: 'Boss',
        };
    }
}

module.exports = Boss;
