/**
 * MockDemoAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Employee = require('../lib/Models/Employee');
const Boss = require('../lib/Models/Boss');
const Person = require('../lib/Models/Person');
const EmojiResponse = require('../lib/Models/EmojiResponse');

const classMap = {
    Employee,
    Boss,
    Person,
    EmojiResponse,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
